language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22
before_install:
 - chmod +x gradlew
script: ./gradlew assembleDebug
deploy:
      provider: releases
      api_key: "c8526dab1810234341695d47e399f7b76e411445"
      file: ${TRAVIS_BUILD_DIR}/app/build/outputs/apk/app-travis.apk
      on:
        repo: raffysommy/Testappk12
        branch: master
        tags: true
        all_branches: true